/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.pantallajuego;

import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;

/**
 *
 * @author abnerhl
 */
public class Base extends javax.swing.JFrame {

    /**
     * Creates new form Base
     */
    public Base() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosUsuario = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblNickName = new javax.swing.JLabel();
        lblPuntosDeVida = new javax.swing.JLabel();
        lblOro = new javax.swing.JLabel();
        pnlDatosTablero = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        scrlPaneTablero = new javax.swing.JScrollPane();
        pnlTablero = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        mnMercado = new javax.swing.JMenu();
        mnBodega = new javax.swing.JMenu();
        mnReportes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Farm - Juego");
        setMinimumSize(new java.awt.Dimension(800, 600));

        lblNombre.setText("Nombre");

        lblNickName.setText("NickName");

        lblPuntosDeVida.setText("Puntos de vida");

        lblOro.setText("Oro");

        javax.swing.GroupLayout pnlDatosUsuarioLayout = new javax.swing.GroupLayout(pnlDatosUsuario);
        pnlDatosUsuario.setLayout(pnlDatosUsuarioLayout);
        pnlDatosUsuarioLayout.setHorizontalGroup(
            pnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosUsuarioLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(lblNickName)
                .addGap(227, 227, 227)
                .addComponent(lblPuntosDeVida)
                .addGap(247, 247, 247)
                .addComponent(lblOro)
                .addGap(320, 320, 320))
        );
        pnlDatosUsuarioLayout.setVerticalGroup(
            pnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblPuntosDeVida)
                    .addComponent(lblOro)
                    .addComponent(lblNickName))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDatosTableroLayout = new javax.swing.GroupLayout(pnlDatosTablero);
        pnlDatosTablero.setLayout(pnlDatosTableroLayout);
        pnlDatosTableroLayout.setHorizontalGroup(
            pnlDatosTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDatosTableroLayout.setVerticalGroup(
            pnlDatosTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        scrlPaneTablero.setToolTipText("");

        javax.swing.GroupLayout pnlTableroLayout = new javax.swing.GroupLayout(pnlTablero);
        pnlTablero.setLayout(pnlTableroLayout);
        pnlTableroLayout.setHorizontalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1031, Short.MAX_VALUE)
        );
        pnlTableroLayout.setVerticalGroup(
            pnlTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );

        scrlPaneTablero.setViewportView(pnlTablero);

        mnArchivo.setText("Archivo");
        jMenuBar1.add(mnArchivo);

        mnMercado.setText("Mercado");
        jMenuBar1.add(mnMercado);

        mnBodega.setText("Bodega");
        jMenuBar1.add(mnBodega);

        mnReportes.setText("Reportes");
        jMenuBar1.add(mnReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlPaneTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 976, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatosTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatosTablero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(scrlPaneTablero))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblNickName;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOro;
    private javax.swing.JLabel lblPuntosDeVida;
    private javax.swing.JMenu mnArchivo;
    private javax.swing.JMenu mnBodega;
    private javax.swing.JMenu mnMercado;
    private javax.swing.JMenu mnReportes;
    private javax.swing.JPanel pnlDatosTablero;
    private javax.swing.JPanel pnlDatosUsuario;
    private javax.swing.JPanel pnlTablero;
    private javax.swing.JScrollPane scrlPaneTablero;
    // End of variables declaration//GEN-END:variables

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }



    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public JLabel getLblNickName() {
        return lblNickName;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public JLabel getLblOro() {
        return lblOro;
    }

    public JLabel getLblPuntosDeVida() {
        return lblPuntosDeVida;
    }

    public JMenu getMnArchivo() {
        return mnArchivo;
    }

    public JMenu getMnBodega() {
        return mnBodega;
    }

    public JMenu getMnMercado() {
        return mnMercado;
    }

    public JMenu getMnReportes() {
        return mnReportes;
    }

    public JPanel getPnlDatosTablero() {
        return pnlDatosTablero;
    }

    public JPanel getPnlDatosUsuario() {
        return pnlDatosUsuario;
    }

    public JPanel getPnlTablero() {
        return pnlTablero;
    }

    public void setLblNickName(JLabel lblNickName) {
        this.lblNickName = lblNickName;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public void setLblOro(JLabel lblOro) {
        this.lblOro = lblOro;
    }

    public void setLblPuntosDeVida(JLabel lblPuntosDeVida) {
        this.lblPuntosDeVida = lblPuntosDeVida;
    }

    public JScrollPane getScrlPaneTablero() {
        return scrlPaneTablero;
    }

    
    
}