/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.inicio;

/**
 *
 * @author abnerhl
 */
public class VBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    public VBienvenida() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNombre = new javax.swing.JLabel();
        lbNickName = new javax.swing.JLabel();
        txtFNombre = new javax.swing.JTextField();
        txtFNickName = new javax.swing.JTextField();
        btnInicioPartida = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnCrearPlantas = new javax.swing.JButton();
        btnCrearAnimales = new javax.swing.JButton();
        btnCrearProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Farm");
        setName("Bienvenida"); // NOI18N

        lbNombre.setText("Nombre");

        lbNickName.setText("NickName");

        txtFNombre.setToolTipText("");
        txtFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNombreActionPerformed(evt);
            }
        });

        txtFNickName.setToolTipText("");
        txtFNickName.setName(""); // NOI18N
        txtFNickName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNickNameActionPerformed(evt);
            }
        });

        btnInicioPartida.setText("Iniciar partida");
        btnInicioPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioPartidaActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnCrearPlantas.setText("Crear plantas");

        btnCrearAnimales.setText("Crear animales");
        btnCrearAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAnimalesActionPerformed(evt);
            }
        });

        btnCrearProductos.setText("Crear productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicioPartida)
                    .addComponent(txtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNickName)
                    .addComponent(lbNombre)
                    .addComponent(txtFNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearPlantas)
                    .addComponent(btnCrearAnimales)
                    .addComponent(btnCrearProductos))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lbNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lbNickName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnInicioPartida))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnCrearPlantas)
                        .addGap(71, 71, 71)
                        .addComponent(btnCrearAnimales)
                        .addGap(64, 64, 64)
                        .addComponent(btnCrearProductos)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNombreActionPerformed

    private void txtFNickNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNickNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNickNameActionPerformed

    private void btnInicioPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioPartidaActionPerformed

    private void btnCrearAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAnimalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearAnimalesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearAnimales;
    private javax.swing.JButton btnCrearPlantas;
    private javax.swing.JButton btnCrearProductos;
    private javax.swing.JButton btnInicioPartida;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbNickName;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JTextField txtFNickName;
    private javax.swing.JTextField txtFNombre;
    // End of variables declaration//GEN-END:variables
}
