/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panelesdeinformacion.grama;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author abnerhl
 */
public class GramaAnimal extends javax.swing.JPanel {

    /**
     * Creates new form GramaAnimal
     */
    public GramaAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnObtenerProduccion = new javax.swing.JButton();
        btnDestazar = new javax.swing.JButton();
        lblTipoAnimal = new javax.swing.JLabel();
        lblPuntosVida = new javax.swing.JLabel();
        lblHambre = new javax.swing.JLabel();

        btnObtenerProduccion.setText("Obtener produccion");

        btnDestazar.setText("Destazar");

        lblTipoAnimal.setText("Tipo del Animal");

        lblPuntosVida.setText("Puntos de Vida");

        lblHambre.setText("Hambre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHambre)
                    .addComponent(lblPuntosVida)
                    .addComponent(btnDestazar)
                    .addComponent(btnObtenerProduccion)
                    .addComponent(lblTipoAnimal))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTipoAnimal)
                .addGap(18, 18, 18)
                .addComponent(lblPuntosVida)
                .addGap(18, 18, 18)
                .addComponent(lblHambre)
                .addGap(103, 103, 103)
                .addComponent(btnObtenerProduccion)
                .addGap(18, 18, 18)
                .addComponent(btnDestazar)
                .addContainerGap(412, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDestazar;
    private javax.swing.JButton btnObtenerProduccion;
    private javax.swing.JLabel lblHambre;
    private javax.swing.JLabel lblPuntosVida;
    private javax.swing.JLabel lblTipoAnimal;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnDestazar() {
        return btnDestazar;
    }

    public JButton getBtnObtenerProduccion() {
        return btnObtenerProduccion;
    }

    public JLabel getLblHambre() {
        return lblHambre;
    }

    public JLabel getLblPuntosVida() {
        return lblPuntosVida;
    }

    public JLabel getLblTipoAnimal() {
        return lblTipoAnimal;
    }

    

}
