/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panelesdeinformacion.grama;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author abnerhl
 */
public class GramaLimpia extends javax.swing.JPanel {

    /**
     * Creates new form gramaLimpia
     */
    public GramaLimpia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEstadoCompra = new javax.swing.JLabel();
        lblEstadoDisponibilidad = new javax.swing.JLabel();
        btnCrearAnimal = new javax.swing.JButton();
        btnCrearPlanta = new javax.swing.JButton();

        lblEstadoCompra.setText("Estado de compra:");

        lblEstadoDisponibilidad.setText("E:stado de disponibilidad:");

        btnCrearAnimal.setText("Crear animal");

        btnCrearPlanta.setText("Crear planta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearPlanta)
                    .addComponent(btnCrearAnimal)
                    .addComponent(lblEstadoDisponibilidad)
                    .addComponent(lblEstadoCompra))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblEstadoCompra)
                .addGap(31, 31, 31)
                .addComponent(lblEstadoDisponibilidad)
                .addGap(90, 90, 90)
                .addComponent(btnCrearAnimal)
                .addGap(41, 41, 41)
                .addComponent(btnCrearPlanta)
                .addContainerGap(413, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearAnimal;
    private javax.swing.JButton btnCrearPlanta;
    private javax.swing.JLabel lblEstadoCompra;
    private javax.swing.JLabel lblEstadoDisponibilidad;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCrearAnimal() {
        return btnCrearAnimal;
    }

    public JButton getBtnCrearPlanta() {
        return btnCrearPlanta;
    }

    public JLabel getLblEstadoCompra() {
        return lblEstadoCompra;
    }

    public JLabel getLblEstadoDisponibilidad() {
        return lblEstadoDisponibilidad;
    }

    

}
